# Generated by Django 5.0.4 on 2024-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('admin_photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('manufacturer_photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('personalization', models.CharField(blank=True, max_length=100, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('main_stone1', models.CharField(blank=True, max_length=100, null=True)),
                ('main_stone2', models.CharField(blank=True, max_length=100, null=True)),
                ('main_stone3', models.CharField(blank=True, max_length=100, null=True)),
                ('main_stone4', models.CharField(blank=True, max_length=100, null=True)),
                ('side_stone1', models.CharField(blank=True, max_length=100, null=True)),
                ('side_stone2', models.CharField(blank=True, max_length=100, null=True)),
                ('side_stone3', models.CharField(blank=True, max_length=100, null=True)),
                ('side_stone4', models.CharField(blank=True, max_length=100, null=True)),
                ('material_used1', models.CharField(blank=True, max_length=100, null=True)),
                ('material_used2', models.CharField(blank=True, max_length=100, null=True)),
                ('material_used3', models.CharField(blank=True, max_length=100, null=True)),
                ('material_used4', models.CharField(blank=True, max_length=100, null=True)),
                ('labour1', models.CharField(blank=True, max_length=100, null=True)),
                ('labour2', models.CharField(blank=True, max_length=100, null=True)),
                ('labour3', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_cost', models.FloatField(default=0)),
                ('packaging_cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('original_delivery_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fax_shipping', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
