# Generated by Django 5.0.4 on 2024-04-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='shop_name',
            field=models.CharField(default='DA exports', max_length=100),
            preserve_default=False,
        ),
    ]
