# Generated by Django 5.0.4 on 2024-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_order_id_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fax_shipping',
        ),
        migrations.AddField(
            model_name='item',
            name='fast_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
