# Generated by Django 5.0.4 on 2024-04-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_item_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='labour3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_stone4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='material_used4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='side_stone4',
            field=models.FloatField(default=0),
        ),
    ]
