# Generated by Django 5.0.4 on 2024-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_item_shop_name_item_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deliverypackagesum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='mainsidesum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='materiallaboursum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='optiona1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
