# Generated by Django 5.0.4 on 2024-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='optional11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
