# Generated by Django 5.0.4 on 2024-05-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_item_optional11'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='optiona1',
            new_name='optional1',
        ),
    ]
