# Generated by Django 5.0.4 on 2024-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_optiona1_item_optional1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fast_shipping',
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
