# Generated by Django 5.0.4 on 2024-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_chatnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stone_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
