# Generated by Django 5.0.4 on 2024-06-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_item_stone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stone_status',
            field=models.CharField(default='Stone Pending', max_length=100),
        ),
    ]
