const ukGeography  = [
    {
      id: 0,
      title: "England",
      subs: [
        {
          id: 1,
          title: "Metropolitan districts",
          subs: [
            { id: 101, title: "Barnsley Borough Council" },
            { id: 102, title: "Birmingham City Council" },
            { id: 103, title: "Bolton Borough Council" },
            { id: 104, title: "Bradford City Council" },
            { id: 105, title: "Bury Borough Council" },
            { id: 106, title: "Calderdale Borough Council" },
            { id: 107, title: "Coventry City Council" },
            { id: 108, title: "Doncaster Borough Council" },
            { id: 109, title: "Dudley Borough Council" },
            { id: 110, title: "Gateshead Borough Council" },
            { id: 111, title: "Kirklees Borough Council" },
            { id: 112, title: "Knowsley Borough Council" },
            { id: 113, title: "Leeds City Council" },
            { id: 114, title: "Liverpool City Council" },
            { id: 115, title: "Manchester City Council" },
            { id: 116, title: "North Tyneside Borough Council" },
            { id: 117, title: "Newcastle Upon Tyne City Council" },
            { id: 118, title: "Oldham Borough Council" },
            { id: 119, title: "Rochdale Borough Council" },
            { id: 120, title: "Rotherham Borough Council" },
            { id: 121, title: "South Tyneside Borough Council" },
            { id: 122, title: "Salford City Council" },
            { id: 123, title: "Sandwell Borough Council" },
            { id: 124, title: "Sefton Borough Council" },
            { id: 125, title: "Sheffield City Council" },
            { id: 126, title: "Solihull Borough Council" },
            { id: 127, title: "St Helens Borough Council" },
            { id: 128, title: "Stockport Borough Council" },
            { id: 129, title: "Sunderland City Council" },
            { id: 130, title: "Tameside Borough Council" },
            { id: 131, title: "Trafford Borough Council" },
            { id: 132, title: "Wakefield City Council" },
            { id: 133, title: "Walsall Borough Council" },
            { id: 134, title: "Wigan Borough Council" },
            { id: 135, title: "Wirral Borough Council" },
            { id: 136, title: "Wolverhampton City Council" },
          ],
        },
        {
          id: 2,
          title: "London boroughs",
          subs: [
            { id: 201, title: "Barking and Dagenham" },
            { id: 202, title: "Barnet" },
            { id: 203, title: "Bexley" },
            { id: 204, title: "Brent" },
            { id: 205, title: "Bromley" },
            { id: 206, title: "Camden" },
            { id: 207, title: "Croydon" },
            { id: 208, title: "Ealing" },
            { id: 209, title: "Enfield" },
            { id: 210, title: "Greenwich" },
            { id: 211, title: "Hackney" },
            { id: 212, title: "Hammersmith and Fulham" },
            { id: 213, title: "Haringey" },
            { id: 214, title: "Harrow" },
            { id: 215, title: "Havering" },
            { id: 216, title: "Hillingdon" },
            { id: 217, title: "Hounslow" },
            { id: 218, title: "Islington" },
            { id: 219, title: "Kensington and Chelsea" },
            { id: 220, title: "Kingston upon Thames" },
            { id: 221, title: "Lambeth" },
            { id: 222, title: "Lewisham" },
            { id: 223, title: "Merton" },
            { id: 224, title: "Newham" },
            { id: 225, title: "Redbridge" },
            { id: 226, title: "Richmond upon Thames" },
            { id: 227, title: "Southwark" },
            { id: 228, title: "Sutton" },
            { id: 229, title: "Tower Hamlets" },
            { id: 230, title: "Waltham Forest" },
            { id: 231, title: "Wandsworth" },
            { id: 232, title: "Westminster" },
          ],
        },
        {
          id: 3,
          title: "Unitary authorities",
          subs: [
            { id: 301, title: "Bath and North East Somerset Council" },
            { id: 302, title: "Bedford Borough Council" },
            { id: 303, title: "Blackburn with Darwen Borough Council" },
            { id: 304, title: "Blackpool Borough Council" },
            { id: 305, title: "Bournemouth, Christchurch and Poole Council" },
            { id: 306, title: "Bracknell Forest Council" },
            { id: 307, title: "Brighton and Hove City Council" },
            { id: 308, title: "Bristol City Council" },
            { id: 309, title: "Central Bedfordshire Council" },
            { id: 310, title: "Cheshire East Council" },
            { id: 311, title: "Cheshire West and Chester Council" },
            { id: 312, title: "Cornwall Council" },
            { id: 313, title: "County Durham Council" },
            { id: 314, title: "Darlington Borough Council" },
            { id: 315, title: "Derby City Council" },
            { id: 316, title: "Devon County Council" },
            { id: 317, title: "Dorset Council" },
            { id: 318, title: "East Riding of Yorkshire Council" },
            { id: 319, title: "Halton Borough Council" },
            { id: 320, title: "Hartlepool Borough Council" },
            { id: 321, title: "Herefordshire Council" },
            { id: 322, title: "Hertfordshire County Council" },
            { id: 323, title: "Isle of Wight Council" },
            { id: 324, title: "Isles of Scilly Council" },
            { id: 325, title: "Kingston upon Hull City Council" },
            { id: 326, title: "Lancashire County Council" },
            { id: 327, title: "Leicester City Council" },
            { id: 328, title: "Leicestershire County Council" },
            { id: 329, title: "Lincolnshire County Council" },
            { id: 330, title: "Luton Borough Council" },
            { id: 331, title: "Medway Council" },
            { id: 332, title: "Middlesbrough Borough Council" },
            { id: 333, title: "Milton Keynes Council" },
            { id: 334, title: "Newcastle-under-Lyme Borough Council" },
            { id: 335, title: "Norfolk County Council" },
            { id: 336, title: "North East Lincolnshire Council" },
            { id: 337, title: "North Lincolnshire Council" },
            { id: 338, title: "North Somerset Council" },
            { id: 339, title: "North Tyneside Council" },
            { id: 340, title: "North Yorkshire County Council" },
            { id: 341, title: "Northamptonshire County Council" },
            { id: 342, title: "Northumberland County Council" },
            { id: 343, title: "Nottingham City Council" },
            { id: 344, title: "Nottinghamshire County Council" },
            { id: 345, title: "Oxfordshire County Council" },
            { id: 346, title: "Peterborough City Council" },
            { id: 347, title: "Plymouth City Council" },
            { id: 348, title: "Portsmouth City Council" },
            { id: 349, title: "Reading Borough Council" },
            { id: 350, title: "Redcar and Cleveland Borough Council" },
            { id: 351, title: "Rutland County Council" },
            { id: 352, title: "Shropshire Council" },
            { id: 353, title: "Slough Borough Council" },
            { id: 354, title: "Somerset County Council" },
            { id: 355, title: "South Gloucestershire Council" },
            { id: 356, title: "Southampton City Council" },
            { id: 357, title: "Southend-on-Sea Borough Council" },
            { id: 358, title: "Stoke-on-Trent City Council" },
            { id: 359, title: "Suffolk County Council" },
            { id: 360, title: "Sunderland City Council" },
            { id: 361, title: "Surrey County Council" },
            { id: 362, title: "Swindon Borough Council" },
            { id: 363, title: "Telford and Wrekin Council" },
            { id: 364, title: "Thurrock Council" },
            { id: 365, title: "Torbay Council" },
            { id: 366, title: "Tyne and Wear Authorities" },
            { id: 367, title: "Warrington Borough Council" },
            { id: 368, title: "Warwickshire County Council" },
            { id: 369, title: "West Berkshire Council" },
            { id: 370, title: "West Sussex County Council" },
            { id: 371, title: "Wiltshire Council" },
            { id: 372, title: "Windsor and Maidenhead Council" },
            { id: 373, title: "Wokingham Borough Council" },
            { id: 374, title: "Worcestershire County Council" },
            { id: 375, title: "York City Council" },
          ],
        },
        {
          id: 4,
          title: "County councils",
          subs: [
            { id: 401, title: "Cambridgeshire County Council" },
            { id: 402, title: "Derbyshire County Council" },
            { id: 403, title: "Devon County Council" },
            { id: 404, title: "Dorset Council" },
            { id: 405, title: "Durham County Council" },
            { id: 406, title: "East Sussex County Council" },
            { id: 407, title: "Essex County Council" },
            { id: 408, title: "Gloucestershire County Council" },
            { id: 409, title: "Hampshire County Council" },
            { id: 410, title: "Hertfordshire County Council" },
            { id: 411, title: "Kent County Council" },
            { id: 412, title: "Lancashire County Council" },
            { id: 413, title: "Leicestershire County Council" },
            { id: 414, title: "Lincolnshire County Council" },
            { id: 415, title: "Norfolk County Council" },
            { id: 416, title: "North Yorkshire County Council" },
            { id: 417, title: "Northamptonshire County Council" },
            { id: 418, title: "Northumberland County Council" },
            { id: 419, title: "Nottinghamshire County Council" },
            { id: 420, title: "Oxfordshire County Council" },
            { id: 421, title: "Shropshire County Council" },
            { id: 422, title: "Somerset County Council" },
            { id: 423, title: "Staffordshire County Council" },
            { id: 424, title: "Suffolk County Council" },
            { id: 425, title: "Surrey County Council" },
            { id: 426, title: "Warwickshire County Council" },
            { id: 427, title: "West Sussex County Council" },
            { id: 428, title: "Wiltshire County Council" },
            { id: 429, title: "Worcestershire County Council" },
            { id: 430, title: "Yorkshire County Council" },
          ],
        },
        {
          id: 5,
          title: "District councils",
          subs: [
            { id: 501, title: "Adur District Council" },
            { id: 502, title: "Allerdale District Council" },
            { id: 503, title: "Amber Valley Borough Council" },
            { id: 504, title: "Arun District Council" },
            { id: 505, title: "Ashfield District Council" },
            { id: 506, title: "Ashford Borough Council" },
            { id: 507, title: "Aylesbury Vale District Council" },
            { id: 508, title: "Babergh District Council" },
            { id: 509, title: "Barking and Dagenham London Borough Council" },
            { id: 510, title: "Barnet London Borough Council" },
            { id: 511, title: "Barnsley Borough Council" },
            { id: 512, title: "Barrow-in-Furness Borough Council" },
            { id: 513, title: "Basildon District Council" },
            { id: 514, title: "Basingstoke and Deane Borough Council" },
            { id: 515, title: "Bassetlaw District Council" },
            { id: 516, title: "Bath and North East Somerset Council" },
            { id: 517, title: "Bedford Borough Council" },
            { id: 518, title: "Bexley London Borough Council" },
            { id: 519, title: "Birmingham City Council" },
            { id: 520, title: "Blaby District Council" },
            { id: 521, title: "Blackburn with Darwen Borough Council" },
            { id: 522, title: "Blackpool Borough Council" },
            { id: 523, title: "Bolsover District Council" },
            { id: 524, title: "Bolton Borough Council" },
            { id: 525, title: "Boston Borough Council" },
            { id: 526, title: "Bournemouth, Christchurch and Poole Council" },
            { id: 527, title: "Bracknell Forest Council" },
            { id: 528, title: "Bradford City Council" },
            { id: 529, title: "Braintree District Council" },
            { id: 530, title: "Breckland District Council" },
            { id: 531, title: "Brent London Borough Council" },
            { id: 532, title: "Brentwood Borough Council" },
            { id: 533, title: "Brighton and Hove City Council" },
            { id: 534, title: "Bristol City Council" },
            { id: 535, title: "Broadland District Council" },
            { id: 536, title: "Bromley London Borough Council" },
            { id: 537, title: "Bromsgrove District Council" },
            { id: 538, title: "Broxbourne Borough Council" },
            { id: 539, title: "Broxtowe Borough Council" },
            { id: 540, title: "Burnley Borough Council" },
            { id: 541, title: "Bury Borough Council" },
            { id: 542, title: "Calderdale Borough Council" },
            { id: 543, title: "Cambridge City Council" },
            { id: 544, title: "Cambridge District Council" },
            { id: 545, title: "Cambridgeshire County Council" },
            { id: 546, title: "Camden London Borough Council" },
            { id: 547, title: "Cannock Chase District Council" },
            { id: 548, title: "Canterbury City Council" },
            { id: 549, title: "Carlisle City Council" },
            { id: 550, title: "Castle Point Borough Council" },
            { id: 551, title: "Central Bedfordshire Council" },
            { id: 552, title: "Charnwood District Council" },
            { id: 553, title: "Chelmsford City Council" },
            { id: 554, title: "Cheltenham Borough Council" },
            { id: 555, title: "Cherwell District Council" },
            { id: 556, title: "Cheshire East Council" },
            { id: 557, title: "Cheshire West and Chester Council" },
            { id: 558, title: "Chesterfield Borough Council" },
            { id: 559, title: "Chichester District Council" },
            { id: 560, title: "Chiltern District Council" },
            { id: 561, title: "Chorley Borough Council" },
            { id: 562, title: "Christchurch Borough Council" },
            { id: 563, title: "City of London Corporation" },
            { id: 564, title: "Colchester Borough Council" },
            { id: 565, title: "Copeland Borough Council" },
            { id: 566, title: "Corby Borough Council" },
            { id: 567, title: "Cornwall Council" },
            { id: 568, title: "Cotswold District Council" },
            { id: 569, title: "County Durham Council" },
            { id: 570, title: "Coventry City Council" },
            { id: 571, title: "Craven District Council" },
            { id: 572, title: "Crawley Borough Council" },
            { id: 573, title: "Croydon London Borough Council" },
            { id: 574, title: "Dacorum Borough Council" },
            { id: 575, title: "Darlington Borough Council" },
            { id: 576, title: "Dartford Borough Council" },
            { id: 577, title: "Daventry District Council" },
            { id: 578, title: "Derby City Council" },
            { id: 579, title: "Derbyshire Dales District Council" },
            { id: 580, title: "Devon County Council" },
            { id: 581, title: "Doncaster Borough Council" },
            { id: 582, title: "Dorset Council" },
            { id: 583, title: "Dover District Council" },
            { id: 584, title: "Dudley Borough Council" },
            { id: 585, title: "Ealing London Borough Council" },
            { id: 586, title: "East Cambridgeshire District Council" },
            { id: 587, title: "East Devon District Council" },
            { id: 588, title: "East Hampshire District Council" },
            { id: 589, title: "East Hertfordshire District Council" },
            { id: 590, title: "East Lindsey District Council" },
            { id: 591, title: "East Northamptonshire District Council" },
            { id: 592, title: "East Riding of Yorkshire Council" },
            { id: 593, title: "East Staffordshire Borough Council" },
            { id: 594, title: "East Suffolk District Council" },
            { id: 595, title: "Eastbourne Borough Council" },
            { id: 596, title: "Eastleigh Borough Council" },
            { id: 597, title: "Eden District Council" },
            { id: 598, title: "Elmbridge Borough Council" },
            { id: 599, title: "Enfield London Borough Council" },
            { id: 600, title: "Epping Forest District Council" },
            { id: 601, title: "Epsom and Ewell Borough Council" },
            { id: 602, title: "Erewash Borough Council" },
            { id: 603, title: "Exeter City Council" },
            { id: 604, title: "Fareham Borough Council" },
            { id: 605, title: "Fenland District Council" },
            { id: 606, title: "Folkestone and Hythe District Council" },
            { id: 607, title: "Forest of Dean District Council" },
            { id: 608, title: "Fylde Borough Council" },
            { id: 609, title: "Gateshead Borough Council" },
            { id: 610, title: "Gedling Borough Council" },
            { id: 611, title: "Gloucester City Council" },
            { id: 612, title: "Gloucestershire County Council" },
            { id: 613, title: "Gosport Borough Council" },
            { id: 614, title: "Gravesham Borough Council" },
            { id: 615, title: "Great Yarmouth Borough Council" },
            { id: 616, title: "Greenwich London Borough Council" },
            { id: 617, title: "Guildford Borough Council" },
            { id: 618, title: "Hackney London Borough Council" },
            { id: 619, title: "Halton Borough Council" },
            { id: 620, title: "Hambleton District Council" },
            { id: 621, title: "Hammersmith and Fulham London Borough Council" },
            { id: 622, title: "Harborough District Council" },
            { id: 623, title: "Haringey London Borough Council" },
            { id: 624, title: "Harlow District Council" },
            { id: 625, title: "Harrow London Borough Council" },
            { id: 626, title: "Hart District Council" },
            { id: 627, title: "Hartlepool Borough Council" },
            { id: 628, title: "Hastings Borough Council" },
            { id: 629, title: "Havant Borough Council" },
            { id: 630, title: "Havering London Borough Council" },
            { id: 631, title: "Herefordshire Council" },
            { id: 632, title: "Hertfordshire County Council" },
            { id: 633, title: "Hertsmere Borough Council" },
            { id: 634, title: "High Peak Borough Council" },
            { id: 635, title: "Hillingdon London Borough Council" },
            { id: 636, title: "Hinckley and Bosworth Borough Council" },
            { id: 637, title: "Horsham District Council" },
            { id: 638, title: "Hounslow London Borough Council" },
            { id: 639, title: "Huntingdonshire District Council" },
            { id: 640, title: "Hyndburn Borough Council" },
            { id: 641, title: "Ipswich Borough Council" },
            { id: 642, title: "Isle of Wight Council" },
            { id: 643, title: "Isle of Wight Unitary Authority" },
            { id: 644, title: "Isles of Scilly Council" },
            { id: 645, title: "Kensington and Chelsea London Borough Council" },
            { id: 646, title: "Kettering Borough Council" },
            { id: 647, title: "King's Lynn and West Norfolk Borough Council" },
            { id: 648, title: "Kingston upon Hull City Council" },
            { id: 649, title: "Kingston upon Thames London Borough Council" },
            { id: 650, title: "Kirklees Borough Council" },
            { id: 651, title: "Knowsley Borough Council" },
            { id: 652, title: "Lambeth London Borough Council" },
            { id: 653, title: "Lancaster City Council" },
            { id: 654, title: "Leeds City Council" },
            { id: 655, title: "Leicester City Council" },
            { id: 656, title: "Leicestershire County Council" },
            { id: 657, title: "Lewes District Council" },
            { id: 658, title: "Lewisham London Borough Council" },
            { id: 659, title: "Lichfield District Council" },
            { id: 660, title: "Lincoln City Council" },
            { id: 661, title: "Lincolnshire County Council" },
            { id: 662, title: "Liverpool City Council" },
            { id: 663, title: "Luton Borough Council" },
            { id: 664, title: "Maidstone Borough Council" },
            { id: 665, title: "Maldon District Council" },
            { id: 666, title: "Malvern Hills District Council" },
            { id: 667, title: "Manchester City Council" },
            { id: 668, title: "Mansfield District Council" },
            { id: 669, title: "Medway Council" },
            { id: 670, title: "Melton Borough Council" },
            { id: 671, title: "Mendip District Council" },
            { id: 672, title: "Merseyside Fire and Rescue Authority" },
            { id: 673, title: "Merseyside Police and Crime Commissioner" },
            { id: 674, title: "Merthyr Tydfil County Borough Council" },
            { id: 675, title: "Merton London Borough Council" },
            { id: 676, title: "Mid Devon District Council" },
            { id: 677, title: "Mid Suffolk District Council" },
            { id: 678, title: "Mid Sussex District Council" },
            { id: 679, title: "Middlesbrough Borough Council" },
            { id: 680, title: "Milton Keynes Council" },
            { id: 681, title: "Mole Valley District Council" },
            { id: 682, title: "New Forest District Council" },
            { id: 683, title: "Newark and Sherwood District Council" },
            { id: 684, title: "Newcastle upon Tyne City Council" },
            { id: 685, title: "Newcastle-under-Lyme Borough Council" },
            { id: 686, title: "Newham London Borough Council" },
            { id: 687, title: "North Devon District Council" },
            { id: 688, title: "North Dorset District Council" },
            { id: 689, title: "North East Derbyshire District Council" },
            { id: 690, title: "North East Lincolnshire Council" },
            { id: 691, title: "North Hertfordshire District Council" },
            { id: 692, title: "North Kesteven District Council" },
            { id: 693, title: "North Lincolnshire Council" },
            { id: 694, title: "North Norfolk District Council" },
            { id: 695, title: "North Northamptonshire Unitary Authority" },
            { id: 696, title: "North Somerset Council" },
            { id: 697, title: "North Tyneside Council" },
            { id: 698, title: "North Warwickshire Borough Council" },
            { id: 699, title: "North West Leicestershire District Council" },
            { id: 700, title: "North Yorkshire County Council" },
            { id: 701, title: "Northampton Borough Council" },
            { id: 702, title: "Northamptonshire County Council" },
            { id: 703, title: "Northumberland County Council" },
            { id: 704, title: "Norwich City Council" },
            { id: 705, title: "Nottingham City Council" },
            { id: 706, title: "Nuneaton and Bedworth Borough Council" },
            { id: 707, title: "Oadby and Wigston Borough Council" },
            { id: 708, title: "Oldham Borough Council" },
            { id: 709, title: "Oxford City Council" },
            { id: 710, title: "Oxfordshire County Council" },
            { id: 711, title: "Pendle Borough Council" },
            { id: 712, title: "Peterborough City Council" },
            { id: 713, title: "Plymouth City Council" },
            { id: 714, title: "Poole Borough Council" },
            { id: 715, title: "Portsmouth City Council" },
            { id: 716, title: "Preston City Council" },
            { id: 717, title: "Reading Borough Council" },
            { id: 718, title: "Redbridge London Borough Council" },
            { id: 719, title: "Redcar and Cleveland Borough Council" },
            { id: 720, title: "Redditch Borough Council" },
            { id: 721, title: "Reigate and Banstead Borough Council" },
            { id: 722, title: "Ribble Valley Borough Council" },
            { id: 723, title: "Richmond upon Thames London Borough Council" },
            { id: 724, title: "Richmondshire District Council" },
            { id: 725, title: "Rochdale Borough Council" },
            { id: 726, title: "Rochford District Council" },
            { id: 727, title: "Rossendale Borough Council" },
            { id: 728, title: "Rother District Council" },
            { id: 729, title: "Rotherham Borough Council" },
            { id: 730, title: "Rugby Borough Council" },
            { id: 731, title: "Runnymede Borough Council" },
            { id: 732, title: "Rushcliffe Borough Council" },
            { id: 733, title: "Rushmoor Borough Council" },
            { id: 734, title: "Rutland County Council" },
            { id: 735, title: "Ryedale District Council" },
            { id: 736, title: "Salford City Council" },
            { id: 737, title: "Sandwell Borough Council" },
            { id: 738, title: "Scarborough Borough Council" },
            { id: 739, title: "Sedgemoor District Council" },
            { id: 740, title: "Sefton Borough Council" },
            { id: 741, title: "Selby District Council" },
            { id: 742, title: "Sevenoaks District Council" },
            { id: 743, title: "Sheffield City Council" },
            { id: 744, title: "Shepway District Council" },
            { id: 745, title: "Shropshire Council" },
            { id: 746, title: "Slough Borough Council" },
            { id: 747, title: "Solihull Borough Council" },
            { id: 748, title: "Somerset County Council" },
            { id: 749, title: "South Bucks District Council" },
            { id: 750, title: "South Cambridgeshire District Council" },
            { id: 751, title: "South Derbyshire District Council" },
            { id: 752, title: "South Gloucestershire Council" },
            { id: 753, title: "South Hams District Council" },
            { id: 754, title: "South Holland District Council" },
            { id: 755, title: "South Kesteven District Council" },
            { id: 756, title: "South Lakeland District Council" },
            { id: 757, title: "South Norfolk District Council" },
            { id: 758, title: "South Northamptonshire District Council" },
            { id: 759, title: "South Oxfordshire District Council" },
            { id: 760, title: "South Ribble Borough Council" },
            { id: 761, title: "South Somerset District Council" },
            { id: 762, title: "South Staffordshire District Council" },
            { id: 763, title: "South Tyneside Borough Council" },
            { id: 764, title: "Southampton City Council" },
            { id: 765, title: "Southend-on-Sea Borough Council" },
            { id: 766, title: "Southwark London Borough Council" },
            { id: 767, title: "Spelthorne Borough Council" },
            { id: 768, title: "St Albans City and District Council" },
            { id: 769, title: "St Edmundsbury Borough Council" },
            { id: 770, title: "St Helens Borough Council" },
            { id: 771, title: "Stafford Borough Council" },
            { id: 772, title: "Staffordshire County Council" },
            { id: 773, title: "Staffordshire Moorlands District Council" },
            { id: 774, title: "Stevenage Borough Council" },
            { id: 775, title: "Stockport Borough Council" },
            { id: 776, title: "Stockton-on-Tees Borough Council" },
            { id: 777, title: "Stoke-on-Trent City Council" },
            { id: 778, title: "Stratford-on-Avon District Council" },
            { id: 779, title: "Stroud District Council" },
            { id: 780, title: "Suffolk Coastal District Council" },
            { id: 781, title: "Suffolk County Council" },
            { id: 782, title: "Sunderland City Council" },
            { id: 783, title: "Surrey County Council" },
            { id: 784, title: "Sutton London Borough Council" },
            { id: 785, title: "Swale Borough Council" },
            { id: 786, title: "Swindon Borough Council" },
            { id: 787, title: "Tameside Borough Council" },
            { id: 788, title: "Tamworth Borough Council" },
            { id: 789, title: "Tandridge District Council" },
            { id: 790, title: "Taunton Deane Borough Council" },
            { id: 791, title: "Teignbridge District Council" },
            { id: 792, title: "Telford and Wrekin Council" },
            { id: 793, title: "Tendring District Council" },
            { id: 794, title: "Test Valley Borough Council" },
            { id: 795, title: "Tewkesbury Borough Council" },
            { id: 796, title: "Thanet District Council" },
            { id: 797, title: "Three Rivers District Council" },
            { id: 798, title: "Thurrock Council" },
            { id: 799, title: "Tonbridge and Malling Borough Council" },
            { id: 800, title: "Torbay Council" },
            { id: 801, title: "Torridge District Council" },
            { id: 802, title: "Tower Hamlets London Borough Council" },
            { id: 803, title: "Trafford Borough Council" },
            { id: 804, title: "Tunbridge Wells Borough Council" },
            { id: 805, title: "Uttlesford District Council" },
            { id: 806, title: "Vale of White Horse District Council" },
            { id: 807, title: "Wakefield City Council" },
            { id: 808, title: "Walsall Borough Council" },
            { id: 809, title: "Waltham Forest London Borough Council" },
            { id: 810, title: "Wandsworth London Borough Council" },
            { id: 811, title: "Warrington Borough Council" },
            { id: 812, title: "Warwick District Council" },
            { id: 813, title: "Warwickshire County Council" },
            { id: 814, title: "Watford Borough Council" },
            { id: 815, title: "Waverley Borough Council" },
            { id: 816, title: "Wealden District Council" },
            { id: 817, title: "Wellingborough Borough Council" },
            { id: 818, title: "Welwyn Hatfield Borough Council" },
            { id: 819, title: "West Berkshire Council" },
            { id: 820, title: "West Devon Borough Council" },
            { id: 821, title: "West Dorset District Council" },
            { id: 822, title: "West Lancashire Borough Council" },
            { id: 823, title: "West Lindsey District Council" },
            { id: 824, title: "West Oxfordshire District Council" },
            { id: 825, title: "West Somerset District Council" },
            { id: 826, title: "West Sussex County Council" },
            { id: 827, title: "Westminster City Council" },
            { id: 828, title: "Weymouth and Portland Borough Council" },
            { id: 829, title: "Wigan Borough Council" },
            { id: 830, title: "Wiltshire Council" },
            { id: 831, title: "Winchester City Council" },
            { id: 832, title: "Windsor and Maidenhead Borough Council" },
            { id: 833, title: "Wirral Borough Council" },
            { id: 834, title: "Woking Borough Council" },
            { id: 835, title: "Wokingham Borough Council" },
            { id: 836, title: "Wolverhampton City Council" },
            { id: 837, title: "Worcester City Council" },
            { id: 838, title: "Worcestershire County Council" },
            { id: 839, title: "Worthing Borough Council" },
            { id: 840, title: "Wychavon District Council" },
            { id: 841, title: "Wycombe District Council" },
            { id: 842, title: "Wyre Borough Council" },
            { id: 843, title: "Wyre Forest District Council" },
            { id: 844, title: "York City Council" },
          ],
        },
      ],
    },
    {
      id: 20,
      title: "Scotland",
      subs: [
        { id: 2001, title: "Aberdeen City Council" },
        { id: 2002, title: "Aberdeenshire Council" },
        { id: 2003, title: "Angus Council" },
        { id: 2004, title: "Argyll and Bute Council" },
        { id: 2005, title: "Clackmannanshire Council" },
        { id: 2006, title: "Dumfries and Galloway Council" },
        { id: 2007, title: "Dundee City Council" },
        { id: 2008, title: "East Ayrshire Council" },
        { id: 2009, title: "East Dunbartonshire Council" },
        { id: 2010, title: "East Lothian Council" },
        { id: 2011, title: "East Renfrewshire Council" },
        { id: 2012, title: "Edinburgh City Council" },
        { id: 2013, title: "Falkirk Council" },
        { id: 2014, title: "Fife Council" },
        { id: 2015, title: "Glasgow City Council" },
        { id: 2016, title: "Highland Council" },
        { id: 2017, title: "Inverclyde Council" },
        { id: 2018, title: "Midlothian Council" },
        { id: 2019, title: "Moray Council" },
        { id: 2020, title: "Na h-Eileanan Siar (Western Isles Council)" },
        { id: 2021, title: "North Ayrshire Council" },
        { id: 2022, title: "North Lanarkshire Council" },
        { id: 2023, title: "Orkney Islands Council" },
        { id: 2024, title: "Perth and Kinross Council" },
        { id: 2025, title: "Renfrewshire Council" },
        { id: 2026, title: "Scottish Borders Council" },
        { id: 2027, title: "Shetland Islands Council" },
        { id: 2028, title: "South Ayrshire Council" },
        { id: 2029, title: "South Lanarkshire Council" },
        { id: 2030, title: "Stirling Council" },
        { id: 2031, title: "West Dunbartonshire Council" },
        { id: 2032, title: "West Lothian Council" },
      ],
    },
    {
      id: 30,
      title: "Wales",
      subs: [
        { id: 3001, title: "Blaenau Gwent County Borough Council" },
        { id: 3002, title: "Bridgend County Borough Council" },
        { id: 3003, title: "Caerphilly County Borough Council" },
        { id: 3004, title: "Cardiff City Council" },
        { id: 3005, title: "Carmarthenshire County Council" },
        { id: 3006, title: "Ceredigion County Council" },
        { id: 3007, title: "Conwy County Borough Council" },
        { id: 3008, title: "Denbighshire County Council" },
        { id: 3009, title: "Flintshire County Council" },
        { id: 3010, title: "Gwynedd Council" },
        { id: 3011, title: "Isle of Anglesey County Council" },
        { id: 3012, title: "Merthyr Tydfil County Borough Council" },
        { id: 3013, title: "Monmouthshire County Council" },
        { id: 3014, title: "Neath Port Talbot County Borough Council" },
        { id: 3015, title: "Newport City Council" },
        { id: 3016, title: "Pembrokeshire County Council" },
        { id: 3017, title: "Powys County Council" },
        { id: 3018, title: "Rhondda Cynon Taf County Borough Council" },
        { id: 3019, title: "Swansea City and County Council" },
        { id: 3020, title: "Torfaen County Borough Council" },
        { id: 3021, title: "Vale of Glamorgan Council" },
        { id: 3022, title: "Wrexham County Borough Council" },
      ],
    },
  ];
  
//   console.log(ukGeography);
  export { ukGeography };