# Generated by Django 5.0.4 on 2024-06-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('manufacturer', 'Manufacturer'), ('admin', 'Admin'), ('shop', 'Shop'), ('designer', 'Designer')], default='employee', max_length=100),
        ),
    ]
